[build]
  publish = "."
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/paiement"
  to = "/paiement.html"
  status = 200

[[redirects]]
  from = "/paiement-success"
  to = "/paiement-success.html"
  status = 200

[[functions]]
  path = "/.netlify/functions/send-weekly-reminder"

[functions.send-weekly-reminder]
  schedule = "0 9 * * 1"
